Repository brewsci/homebrew-science, pull requests merged in 2018-04, with the labels that each got.

#126 lastz: migrate
  Formula/lastz.rb
  tap_migrations.json
Labels: migrate

#125 last: migrate
  Formula/last.rb
  tap_migrations.json
Labels: migrate

#124 dwgsim: migrate
  Formula/dwgsim.rb
  tap_migrations.json
Labels: migrate

#129 tap_migrations.json: Fix a typo
  tap_migrations.json
Labels: bug

#128 r8s: migrate
  Formula/r8s.rb
  tap_migrations.json
Labels: migrate

#134 biobloomtools: migrate to brewsci/bio
  Formula/biobloomtools.rb
  tap_migrations.json
Labels: migrate

#131 libpll: migrate
  Formula/libpll.rb
  tap_migrations.json
Labels: migrate

#132 astral: migrate to brewsci/bio
  Formula/astral.rb
  tap_migrations.json
Labels: migrate

#133 bamm: migrate to brewsci/bio
  Formula/bamm.rb
  tap_migrations.json
Labels: migrate

#138 phlawd: migrate
  Formula/phlawd.rb
  tap_migrations.json
Labels: migrate

#141 Remove :run from depends_on
  Formula/dealii.rb
  Formula/geant4.rb
  Formula/ggobi.rb
  Formula/gnudatalanguage.rb
  Formula/libbi.rb
  Formula/mlpack.rb
  Formula/nest.rb
  Formula/pandaseq.rb
  Formula/pocl.rb
  Formula/reapr.rb
Labels: bug

#139 nxtrim: migrate to brewsci/bio
  Formula/nxtrim.rb
  tap_migrations.json
Labels: migrate

#142 vcflib: migrate
  Formula/vcflib.rb
  tap_migrations.json
Labels: migrate

#143 freebayes: migrate
  Formula/freebayes.rb
  tap_migrations.json
Labels: migrate

#144 mafft: migrated to CORE
  Formula/mafft.rb
  tap_migrations.json
Labels: migrate

#145 cfml: migrate
  Formula/clonalframeml.rb
  tap_migrations.json
Labels: migrate

#147 fasttree: migrate to bio
  Formula/fasttree.rb
  tap_migrations.json
Labels: migrate

#148 Snp sites.migrate from
  Formula/snp-sites.rb
  tap_migrations.json
Labels: migrate

#146 megahit: migrate to bio
  Formula/megahit.rb
  tap_migrations.json
Labels: migrate

#149 prank: migrate
  Formula/prank.rb
  tap_migrations.json
Labels: migrate

#123 elph: migrate
  Formula/elph.rb
  tap_migrations.json
Labels: migrate

#151 hisat2: migrate to brewsci/bio
  Formula/hisat2.rb
  tap_migrations.json
Labels: migrate

#107 beast2: migrate
  Formula/beast2.rb
  tap_migrations.json
Labels: migrate, stale

#154 beagle: migrate to brewsci/bio
  Formula/beagle.rb
  tap_migrations.json
Labels: migrate

#156 centrifuge: migrate
  Formula/centrifuge.rb
  tap_migrations.json
Labels: migrate

#157 andi: migrate
  Formula/andi.rb
  tap_migrations.json
Labels: migrate

#155 cd-hit: migrate
  Formula/cd-hit.rb
  tap_migrations.json
Labels: migrate

#158 idba: migrate
  Formula/idba.rb
  tap_migrations.json
Labels: migrate

#162 k8: migrate
  Formula/k8.rb
  tap_migrations.json
Labels: migrate

#163 fasta: migrate
  Formula/fasta.rb
  tap_migrations.json
Labels: migrate

#159 blat: migrate to brewsci/bio
  Formula/blat.rb
  tap_migrations.json
Labels: migrate
